Repository timerring/bilitool, pull requests merged in 2025-01, with the labels that each got.

#1 build: change package dependencies
  .gitignore
  biliupload/upload/bili_upload.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#2 chore: add issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs-feedback.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help-wanted.md
  .github/pull_request_template.md
Labels: documentation

#4 refactor: refactor entire code
  .gitignore
  biliupload/cli.py
  biliupload/config.json
  biliupload/controller/__init__.py
  biliupload/controller/upload_controller.py
  biliupload/ioer.py
  biliupload/login/login_bili.py
  biliupload/upload/bili_upload.py
Labels: enhancement

#5 feat: restore upload parameters
  README-en.md
  README.md
  biliupload/cli.py
  biliupload/config.json
  biliupload/ioer.py
  biliupload/upload/bili_upload.py
  biliupload/utils/parse_yaml.py
  template/example-config.yaml
Labels: enhancement

#6 build: build version 0.0.2
  README-en.md
  README.md
  biliupload/cli.py
  pyproject.toml
Labels: build

#7 feat: add check login module
  biliupload/cli.py
  biliupload/login/check_login.py
Labels: feature

#8 feat: add logout module
  biliupload/cli.py
  biliupload/config.json
  biliupload/ioer.py
  biliupload/login/login_bili.py
  biliupload/login/logout_bili.py
Labels: feature

#9 feat: add download module
  biliupload/cli.py
  biliupload/config.json
  biliupload/controller/download_controller.py
  biliupload/controller/upload_controller.py
  biliupload/download/__init__.py
  biliupload/download/bili_download.py
  biliupload/ioer.py
Labels: feature

#10 build: build version 0.0.3
  README-en.md
  README.md
  pyproject.toml
Labels: build

#11 fix: Error decoding command output on Windows
  biliupload/login/login_bili.py
Labels: good first issue, fix

#12 feat: add query ip module
  biliupload/cli.py
  biliupload/utils/get_ip_info.py
  tests/__init__.py
  tests/test_get_ip_info.py
Labels: feature

#14 refactor: add headers decorator
  biliupload/download/bili_download.py
  biliupload/ioer.py
Labels: enhancement

#15 feat: add wbi sign module
  biliupload/authenticate/__init__.py
  biliupload/authenticate/wbi_sign.py
Labels: feature

#16 feat: list uploaded videos module
  biliupload/cli.py
  biliupload/feed/__init__.py
  biliupload/feed/bili_video_list.py
  tests/test_feed.py
Labels: feature

#17 refactor: adjust structure and rename project
  LICENSE
  README-en.md
  README.md
  bilitool/__init__.py
  bilitool/authenticate/__init__.py
  bilitool/authenticate/config.json
  bilitool/authenticate/ioer.py
  bilitool/authenticate/wbi_sign.py
  bilitool/cli.py
  bilitool/controller/__init__.py
  bilitool/controller/download_controller.py
  bilitool/controller/upload_controller.py
  bilitool/download/__init__.py
  bilitool/download/bili_download.py
  bilitool/feed/__init__.py
  bilitool/feed/bili_video_list.py
  bilitool/login/__init__.py
  bilitool/login/check_login.py
  bilitool/login/login_bili.py
  bilitool/login/logout_bili.py
  bilitool/upload/__init__.py
  bilitool/upload/bili_upload.py
  bilitool/utils/__init__.py
  bilitool/utils/get_ip_info.py
  bilitool/utils/parse_cookies.py
  bilitool/utils/parse_yaml.py
  pyproject.toml
  tests/test_feed.py
  tests/test_get_ip_info.py
Labels: enhancement

#18 build: production version v0.1.0
  README-en.md
  README.md
  bilitool/cli.py
Labels: build

#19 refactor: optimize the unittest preformance
  bilitool/utils/get_ip_info.py
  tests/test_utils.py
Labels: enhancement

#20 feat: add vid convert module
  bilitool/cli.py
  bilitool/utils/check_format.py
  tests/test_utils.py
Labels: feature

#21 feat: support both vid download
  bilitool/cli.py
  bilitool/utils/check_format.py
Labels: enhancement

#22 feat: add tqdm progress bar
  README.md
  bilitool/download/bili_download.py
  bilitool/upload/bili_upload.py
  pyproject.toml
Labels: enhancement

#24 build: build version v0.1.1
  README-en.md
  README.md
  bilitool/cli.py
  pyproject.toml
  requirements.txt
Labels: build

#25 ci: add nuitka build ci
  .github/workflows/main.yml
Labels: build

#26 chore: add shasum script
  sha256sum.sh
Labels: enhancement

#28 perf: add detailed logs
  bilitool/cli.py
  bilitool/controller/download_controller.py
  bilitool/download/bili_download.py
Labels: enhancement

#31 refactor: adjust architecture
  .github/workflows/build.yml
  bilitool/authenticate/wbi_sign.py
  bilitool/cli.py
  bilitool/controller/download_controller.py
  bilitool/controller/feed_controller.py
  bilitool/controller/login_controller.py
  bilitool/controller/upload_controller.py
  bilitool/download/bili_download.py
  bilitool/feed/bili_video_list.py
  bilitool/login/check_bili_login.py
  bilitool/login/login_bili.py
  bilitool/login/logout_bili.py
  bilitool/model/__init__.py
  bilitool/model/config.json
  bilitool/model/model.py
  bilitool/upload/bili_upload.py
Labels: enhancement

#33 build: build version v0.1.2
  bilitool/cli.py
  pyproject.toml
Labels: build
